version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)-8s - [%(levelname)] - %(levelname)s - %(message)s'
  default:
    format: '[%(asctime)s][%(levelname)s][%(name)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  logstash:
    class: logstash_async.formatter.LogstashFormatter
    format: format
    datefmt: apbot
    style: True
handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level   : INFO
    stream  : ext://sys.stdout
  monitoring:
    class : logstash_async.handler.AsynchronousLogstashHandler
    formatter: logstash
    level: INFO
    host: 1.232.228.35
    port: 5959
    encoding: utf-8
    database_path: logstash.db
    transport: logstash_async.transport.HttpTransport
    enable: True

loggers:
  simpleExample:
    level: INFO
    handlers: [console]
    propagate: no
  naver:
    level: INFO
    handlers: [ console ]
  tistory:
    level: INFO
    handlers: [ console ]
  main:
    level: INFO
    handlers: [ console ]
  monitoring:
    level: INFO
    handlers: [ monitoring ]
  doc:
      level: INFO
      handlers: [ monitoring, console ]
root:
  level: INFO
  handlers: [console]