version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)-8s - [%(levelname)] - %(levelname)s - %(message)s'
  default:
    format: '[%(asctime)s][%(levelname)s][%(name)s] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level   : INFO
    stream  : ext://sys.stdout
  monitoring:
    class : logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: .//logs//monitoring.log
    backupCount: 3
    encoding: utf-8
    when: midnight
  doc_data:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: default
    filename: .//logs//doc_data.log
    backupCount: 3
    encoding: utf-8
    when: midnight

loggers:
  simpleExample:
    level: INFO
    handlers: [console]
    propagate: no
  naver:
    level: INFO
    handlers: [ console ]
  tistory:
    level: INFO
    handlers: [ console ]
  main:
    level: INFO
    handlers: [ console ]
  monitoring:
    level: INFO
    handlers: [ monitoring ]
  doc_data:
      level: INFO
      handlers: [ doc_data, console ]
root:
  level: INFO
  handlers: [console]